{
 "title": "OKchain Validator Home",
 "description": "System Administration Dashboard",
 "tags": [ "internal" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "OKchain Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "okchain_version", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "OKchain Last Block ID",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 7, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "okchain_last_block", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "OKchain Validator",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "okchain_last_block", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "CPU avg（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100"
    }
   ]
  },
  {
   "title": "fd allocated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "node_filefd_allocated" }
   ]
  },
  {
   "title": "OKchain Last Block ID",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "okchain_last_block{version!=\"0.32.10\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "delta(okchain_last_block{version!=\"0.32.10\"}[1h])",
     "legendFormat": "delta-1h"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "description": "\n",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "Total Size"
    },
    {
     "expr": "node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "VPS Memory ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "MemTotal" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "MemUsed"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "MemFree" },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Mem Used %"
    }
   ]
  },
  {
   "title": "load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" }
   ]
  },
  {
   "title": "CPU load over time（%）",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\"}[5m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"user\"}[5m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total[5m])",
     "legendFormat": "{{device}}_I/O%"
    }
   ]
  },
  {
   "title": "disk io",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "disk r/w bytes",
   "type": "graph",
   "description": "Read bytes\nWritten bytes",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "iops", "label": "I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "ESTABLISHED" },
    { "expr": "node_sockstat_TCP_tw", "legendFormat": "TCP_tw" },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens[1m])",
     "legendFormat": "PassiveOpens"
    },
    { "expr": "node_sockstat_TCP_alloc", "legendFormat": "TCP_alloc" },
    { "expr": "node_sockstat_TCP_inuse", "legendFormat": "TCP_inuse" }
   ]
  },
  {
   "title": "Net IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Context Switches vs interrupts (rate 5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total[5m])",
     "legendFormat": "context switches"
    },
    { "expr": "irate(node_intr_total[5m])", "legendFormat": "interrupts" }
   ]
  }
 ]
}